# Criando o service do banco de dados com postgres e docker
 version: "3"
 volumes:
   dados:

 networks:
       bancos:
       web:
       file:
 services: 
  db:
       image: postgres:9.6
       volumes:
        # Criando os scripts do banco de dados - Criando os volumes do banco - scripts
            - dados:/var/lib/postgresql/data
            - ./scripts:/scripts	
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
            networks:
                - banco	    
  frontend:
        image: nginx:1.3
        volumes:
                # Site
             - ./web:/usr/share/nginx/html/
             # configuração do proxy reverso
             - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80	
        networks:
            - web
        depends_on:
            - app
  app:
        image: python:3.6
        volumes:
               #aplicação
               - ./app:/app
        working_dir: /app
        command: bash ./app.sh
        networks:
            - banco
            - web
            - fila
        depends_on:
            - db
        queue:
            image: redis:3.2
            networks:
                - file
        workers:
            image: python:3.6
            volumes:
                - ./worker:/worker
            working_dir: /worker
            command: bash ./app.sh
            networks:
                - fila
            depends_on:
                - queue